### ISSUE TITLE
The `/cloudvision` command does not work correctly

### ISSUE THREAD

**Issue by ubajze** [nautobot/nautobot-plugin-chatops-arista-cloudvision#14]
### Environment
* Python version:  3.6.13
* Nautobot version:  1.1.2
* nautobot-chatops-extension-arista version:  1.0.1

### Expected Behavior
I want to run the command `/cloudvision get-device-configuration` in Slack to see the device configuration.

### Observed Behavior

When I select the device from the dropdown menu, I get an error.

![Screenshot 2021-09-23 at 12 54 58](https://user-images.githubusercontent.com/6861762/134495311-487c518f-b028-4505-b45e-6ca55b145d98.png)

Using the whole command `/cloudvision get-device-configuration nyc-spine-02` works.

### Steps to Reproduce
1. Deploy the plugin and run Nautobot.
2. Execute the command `/cloudvision get-device-configuration` in Slack

**Comment by qduk** [comment]
Closing per @ubajze
